### ISSUE TITLE
build.ts不成功

### ISSUE THREAD

**Issue by 906051999** [stackinspector/ldtstore-homepage#2]
* 执行
``` 
deno run -A --unstable build.ts path\to\wwwroot\ default
deno run -A --unstable build.ts path\to\intl-wwwroot\ intl
```
报错：
```
error: Module not found "file:///var/lib/snapd/void/build.ts".
```

**Comment by stackinspector** [comment]
首先`path\to\wwwroot\`和`path\to\intl-wwwroot\`需要替换成你期望生成的wwwroot所在的路径，这个我觉得从字面上就能理解吧
其次你是在什么环境下执行的

**Comment by 84634E1A607A** [comment]
> error: Module not found "file:///var/lib/snapd/void/build.ts".

当前目录不在git主目录底下？ 我成功了

**Comment by 906051999** [comment]
* snap 下载的 deno 入参文件路径有问题
解决方法：
* 直接下载deno文件，通过`./deno`执行
遇到问题：
* 因为需要git配置文件，放弃部署，感谢开源
