### ISSUE TITLE
Add PowerToys

### ISSUE THREAD

**Issue by 84634E1A607A** [stackinspector/ldtstore-homepage#3]
## Class

其他工具

## Title

Microsoft PowerToys

## Keywords

微软官方工具箱

## Discription

Microsoft PowerToys is a set of utilities for power users to tune and streamline their Windows experience for greater productivity.

微软PowerToys是一套实用程序，高级用户可以调整和简化他们的Windows体验，以提高生产率。

## Download Links

Official Website: https://docs.microsoft.com/en-us/windows/powertoys/

Installation Guide: https://docs.microsoft.com/en-us/windows/powertoys/install

(我不知道中文文档是怎么回事)

Github Repo: https://github.com/microsoft/PowerToys/

Github Download: https://github.com/microsoft/PowerToys/releases/

**Comment by stackinspector** [comment]
感谢你的用心，但是PowerToys这个工具已经根据大家提的建议放在下一批要添加的项目里了，一共有几十个（捂脸
![已经加到配置文件里了](https://user-images.githubusercontent.com/76254954/154829124-bb2a0a9f-08b2-47e8-9959-729d11f98a27.PNG)
